const fs = require('fs');
const path = require('path');

const rootVersionFile = path.join(__dirname, 'version.js');
const srcVersionFile = path.join(__dirname, 'src', 'version.js');
const packageJson = require('./package.json');

// Get version from package.json or use default
const version = packageJson.version || '2.2.0';
const buildDate = new Date().toISOString();

const rootContent = `// Auto-generated by update-version.js
export const APP_VERSION = '${version}';
export const BUILD_DATE = '${buildDate}';
`;

const srcContent = `// Auto-generated version file - DO NOT EDIT MANUALLY
// This file is updated automatically during build
export const APP_VERSION = '${version}';
export const BUILD_DATE = '${buildDate}';
export const CACHE_VERSION = \`devchat-pro-v\${APP_VERSION}\`;
`;

fs.writeFileSync(rootVersionFile, rootContent);
fs.writeFileSync(srcVersionFile, srcContent);
console.log(`✅ Version updated to ${version} (${buildDate})`);

// Update service worker cache version if it exists
const swPath = path.join(__dirname, 'service-worker.js');
if (fs.existsSync(swPath)) {
  let swContent = fs.readFileSync(swPath, 'utf8');
  swContent = swContent.replace(
    /const CACHE_VERSION = '.*';/,
    `const CACHE_VERSION = 'v${version}';`
  );
  fs.writeFileSync(swPath, swContent);
  console.log(`✅ Service Worker cache updated to v${version}`);
}